---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver_config:
      box: chef/ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[CI_Agent::default]
    attributes:
