name             'CI_Agent'
maintainer       'Hans'
maintainer_email 'hans@thoughtworks.com'
license          'All rights reserved'
description      'Installs & configures VMs for the CI workshop'
long_description 'Installs & configures VMs for the CI workshop'
version          '0.1.0'