# Gemfile
source 'http://rubygems.org'
ruby '2.1.0'
 
gem 'tilt', '~> 1.4.1'
gem "sinatra"
gem "haml"
gem "slim"
gem 'rack-google-analytics'
gem 'newrelic_rpm'
gem "json"
gem "rack-test"
gem "simplecov"
gem "travis"
gem "rake"
gem "coffee-script"
gem "therubyracer"
gem "zip"
gem "parallel_tests"

gem "chromedriver-helper", ">= 0.0.8"

gem "activerecord"
gem "sinatra-activerecord"
gem 'data_mapper'
gem "warden"

gem "cucumber"
gem "capybara", ">= 2.4.2"
gem "selenium-webdriver"

group :development, :test do
 gem "shotgun"
 gem 'sqlite3'
 gem "tux"
 gem 'dm-sqlite-adapter'
end

group :production do
 gem 'pg'
 gem 'dm-postgres-adapter'
end


