# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "chef/ubuntu-14.04"
  config.vm.network "forwarded_port", guest: 8080, host: 9080
  config.vm.synced_folder "../Installers", "/Installers"
  
  config.vm.provider :virtualbox do |vb|
    vb.destroy_unused_network_interfaces = true
  end
  
  config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true

  config.vm.provision "chef_solo" do |chef|
    #chef.cookbooks_path = "../cookbooks"
    chef.add_recipe "apt"
    #chef.add_recipe "jenkins"
    chef.add_recipe "git"
    chef.add_recipe "bundler"
    chef.add_recipe "phantomjs"
  end

end
